"""initial schema

Revision ID: 6c76280f0b0b
Revises: 
Create Date: 2026-09-01 21:44:30.564541
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '6c76280f0b0b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('failed_login_count', sa.Integer(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_admin_users'))
    )
    op.create_index(op.f('ix_admin_users_email'), 'admin_users', ['email'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('actor_type', sa.String(length=16), nullable=False),
    sa.Column('actor_id', sa.String(length=64), nullable=True),
    sa.Column('target_user_id', sa.String(length=64), nullable=True),
    sa.Column('target_is_under_13', sa.Boolean(), nullable=True),
    sa.Column('detail', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_occurred_at'), 'audit_logs', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_target_user_id'), 'audit_logs', ['target_user_id'], unique=False)
    op.create_table('bible_characters',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('testament', sa.String(length=8), nullable=True),
    sa.Column('era_tags', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('image_asset_key', sa.String(length=255), nullable=True),
    sa.Column('image_alt_text', sa.String(length=500), nullable=True),
    sa.Column('review_status', sa.String(length=16), nullable=False),
    sa.Column('created_by', sa.String(length=160), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bible_characters'))
    )
    op.create_index(op.f('ix_bible_characters_name'), 'bible_characters', ['name'], unique=False)
    op.create_index(op.f('ix_bible_characters_review_status'), 'bible_characters', ['review_status'], unique=False)
    op.create_table('content_publish_records',
    sa.Column('content_version', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('published_by', sa.String(length=160), nullable=True),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('pack_size_bytes', sa.Integer(), nullable=False),
    sa.Column('min_app_build', sa.Integer(), nullable=False),
    sa.Column('change_summary', sa.String(length=500), nullable=True),
    sa.Column('pack_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('validation_report', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.PrimaryKeyConstraint('content_version', name=op.f('pk_content_publish_records'))
    )
    op.create_table('levels',
    sa.Column('level_number', sa.Integer(), nullable=False),
    sa.Column('timer_seconds', sa.Integer(), nullable=False),
    sa.Column('difficulty_tier', sa.String(length=16), nullable=False),
    sa.Column('character_pool', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('min_questions_required', sa.Integer(), nullable=False),
    sa.Column('is_free_tier', sa.Boolean(), nullable=False),
    sa.Column('variant_mix_targets', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('level_number', name=op.f('pk_levels'))
    )
    op.create_table('rate_limit_counters',
    sa.Column('scope', sa.String(length=64), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('window_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('scope', 'key', 'window_start', name=op.f('pk_rate_limit_counters'))
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('mobile', sa.String(length=32), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('age_group', sa.String(length=16), nullable=True),
    sa.Column('is_under_13', sa.Boolean(), nullable=False),
    sa.Column('account_status', sa.String(length=40), nullable=False),
    sa.Column('primary_auth_provider', sa.String(length=16), nullable=True),
    sa.Column('privacy_accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('privacy_policy_version', sa.String(length=32), nullable=True),
    sa.Column('child_notice_acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notifications_opt_in', sa.Boolean(), nullable=False),
    sa.Column('install_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_session_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('account_deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_account_status'), 'users', ['account_status'], unique=False)
    op.create_index(op.f('ix_users_install_id'), 'users', ['install_id'], unique=False)
    op.create_index(op.f('ix_users_mobile'), 'users', ['mobile'], unique=False)
    op.create_index('ix_users_mobile_name', 'users', ['mobile', 'name'], unique=False)
    op.create_table('ad_impression_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('ad_unit_id', sa.String(length=160), nullable=True),
    sa.Column('ad_format', sa.String(length=16), nullable=False),
    sa.Column('placement', sa.String(length=64), nullable=True),
    sa.Column('is_child_directed', sa.Boolean(), nullable=False),
    sa.Column('ad_personalized', sa.Boolean(), nullable=False),
    sa.Column('clicked', sa.Boolean(), nullable=False),
    sa.Column('level_id', sa.Integer(), nullable=True),
    sa.Column('impressed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_ad_impression_logs_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ad_impression_logs'))
    )
    op.create_index(op.f('ix_ad_impression_logs_impressed_at'), 'ad_impression_logs', ['impressed_at'], unique=False)
    op.create_index(op.f('ix_ad_impression_logs_user_id'), 'ad_impression_logs', ['user_id'], unique=False)
    op.create_table('analytics_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event_name', sa.String(length=64), nullable=False),
    sa.Column('timestamp_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('admin_user_id', sa.Uuid(), nullable=True),
    sa.Column('session_id', sa.String(length=64), nullable=True),
    sa.Column('age_group', sa.String(length=16), nullable=True),
    sa.Column('is_under_13', sa.Boolean(), nullable=True),
    sa.Column('platform', sa.String(length=16), nullable=True),
    sa.Column('app_version', sa.String(length=32), nullable=True),
    sa.Column('os_version', sa.String(length=64), nullable=True),
    sa.Column('device_type', sa.String(length=16), nullable=True),
    sa.Column('properties', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['admin_user_id'], ['admin_users.id'], name=op.f('fk_analytics_events_admin_user_id_admin_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_analytics_events_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_analytics_events'))
    )
    op.create_index('ix_analytics_event_name_time', 'analytics_events', ['event_name', 'timestamp_utc'], unique=False)
    op.create_index(op.f('ix_analytics_events_admin_user_id'), 'analytics_events', ['admin_user_id'], unique=False)
    op.create_index(op.f('ix_analytics_events_event_name'), 'analytics_events', ['event_name'], unique=False)
    op.create_index(op.f('ix_analytics_events_session_id'), 'analytics_events', ['session_id'], unique=False)
    op.create_index(op.f('ix_analytics_events_timestamp_utc'), 'analytics_events', ['timestamp_utc'], unique=False)
    op.create_index(op.f('ix_analytics_events_user_id'), 'analytics_events', ['user_id'], unique=False)
    op.create_index('ix_analytics_user_event', 'analytics_events', ['user_id', 'event_name'], unique=False)
    op.create_table('auth_identities',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.String(length=16), nullable=False),
    sa.Column('provider_subject', sa.String(length=255), nullable=False),
    sa.Column('provider_email', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_auth_identities_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_auth_identities')),
    sa.UniqueConstraint('provider', 'provider_subject', name='uq_auth_identity_provider_subject')
    )
    op.create_index(op.f('ix_auth_identities_user_id'), 'auth_identities', ['user_id'], unique=False)
    op.create_table('level_attempts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('level_id', sa.Integer(), nullable=False),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('question_sequence', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('expected_next_index', sa.Integer(), nullable=False),
    sa.Column('answers', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('timer_seconds', sa.Integer(), nullable=False),
    sa.Column('computed_score', sa.Integer(), nullable=True),
    sa.Column('suspicious', sa.Boolean(), nullable=False),
    sa.Column('rejection_reason', sa.String(length=40), nullable=True),
    sa.Column('invalidated_by', sa.String(length=160), nullable=True),
    sa.Column('install_id', sa.String(length=64), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_level_attempts_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_level_attempts'))
    )
    op.create_index(op.f('ix_level_attempts_install_id'), 'level_attempts', ['install_id'], unique=False)
    op.create_index(op.f('ix_level_attempts_level_id'), 'level_attempts', ['level_id'], unique=False)
    op.create_index(op.f('ix_level_attempts_status'), 'level_attempts', ['status'], unique=False)
    op.create_index(op.f('ix_level_attempts_user_id'), 'level_attempts', ['user_id'], unique=False)
    op.create_index('ix_level_attempts_user_level', 'level_attempts', ['user_id', 'level_id'], unique=False)
    op.create_table('level_completions',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('level_number', sa.Integer(), nullable=False),
    sa.Column('best_score', sa.Integer(), nullable=False),
    sa.Column('attempts_taken', sa.Integer(), nullable=False),
    sa.Column('first_completed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_completed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_level_completions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'level_number', name=op.f('pk_level_completions'))
    )
    op.create_table('parental_consent_records',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('child_user_id', sa.Uuid(), nullable=False),
    sa.Column('method', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('parent_guardian_name', sa.String(length=160), nullable=True),
    sa.Column('parent_relationship', sa.String(length=16), nullable=True),
    sa.Column('parent_email', sa.String(length=255), nullable=True),
    sa.Column('parent_oauth_provider', sa.String(length=16), nullable=True),
    sa.Column('parent_oauth_sub', sa.String(length=255), nullable=True),
    sa.Column('verification_token_hash', sa.String(length=128), nullable=True),
    sa.Column('send_count', sa.Integer(), nullable=False),
    sa.Column('last_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consent_policy_version', sa.String(length=32), nullable=True),
    sa.Column('consented_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('denied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('child_notice_acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['child_user_id'], ['users.id'], name=op.f('fk_parental_consent_records_child_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_parental_consent_records'))
    )
    op.create_index(op.f('ix_parental_consent_records_child_user_id'), 'parental_consent_records', ['child_user_id'], unique=False)
    op.create_index(op.f('ix_parental_consent_records_status'), 'parental_consent_records', ['status'], unique=False)
    op.create_index(op.f('ix_parental_consent_records_verification_token_hash'), 'parental_consent_records', ['verification_token_hash'], unique=False)
    op.create_table('purchase_records',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('store', sa.String(length=16), nullable=False),
    sa.Column('product_id', sa.String(length=160), nullable=False),
    sa.Column('transaction_id', sa.String(length=255), nullable=False),
    sa.Column('original_transaction_id', sa.String(length=255), nullable=True),
    sa.Column('receipt_token', sa.Text(), nullable=True),
    sa.Column('validation_payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('unlock_status', sa.String(length=16), nullable=False),
    sa.Column('validated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('validated_by_provider', sa.Boolean(), nullable=False),
    sa.Column('price_display', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_purchase_records_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_purchase_records'))
    )
    op.create_index(op.f('ix_purchase_records_original_transaction_id'), 'purchase_records', ['original_transaction_id'], unique=False)
    op.create_index(op.f('ix_purchase_records_transaction_id'), 'purchase_records', ['transaction_id'], unique=False)
    op.create_index(op.f('ix_purchase_records_unlock_status'), 'purchase_records', ['unlock_status'], unique=False)
    op.create_index(op.f('ix_purchase_records_user_id'), 'purchase_records', ['user_id'], unique=False)
    op.create_table('questions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('variant_type', sa.String(length=24), nullable=False),
    sa.Column('answer_options', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('correct_answer', sa.String(length=500), nullable=False),
    sa.Column('linked_character_id', sa.Uuid(), nullable=False),
    sa.Column('level_id', sa.Integer(), nullable=False),
    sa.Column('difficulty_tier', sa.String(length=16), nullable=False),
    sa.Column('verse_reference', sa.String(length=120), nullable=True),
    sa.Column('verse_excerpt', sa.Text(), nullable=True),
    sa.Column('image_asset_key', sa.String(length=255), nullable=True),
    sa.Column('image_alt_text', sa.String(length=500), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('review_status', sa.String(length=16), nullable=False),
    sa.Column('created_by', sa.String(length=160), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['level_id'], ['levels.level_number'], name=op.f('fk_questions_level_id_levels'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['linked_character_id'], ['bible_characters.id'], name=op.f('fk_questions_linked_character_id_bible_characters'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_questions'))
    )
    op.create_index(op.f('ix_questions_active'), 'questions', ['active'], unique=False)
    op.create_index(op.f('ix_questions_level_id'), 'questions', ['level_id'], unique=False)
    op.create_index(op.f('ix_questions_linked_character_id'), 'questions', ['linked_character_id'], unique=False)
    op.create_index('ix_questions_pool_lookup', 'questions', ['level_id', 'active', 'review_status'], unique=False)
    op.create_index(op.f('ix_questions_review_status'), 'questions', ['review_status'], unique=False)
    op.create_index(op.f('ix_questions_variant_type'), 'questions', ['variant_type'], unique=False)
    op.create_table('support_requests',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('subject_category', sa.String(length=64), nullable=False),
    sa.Column('message', sa.String(length=4000), nullable=False),
    sa.Column('reply_to', sa.String(length=255), nullable=True),
    sa.Column('app_version', sa.String(length=32), nullable=True),
    sa.Column('entry_source', sa.String(length=64), nullable=True),
    sa.Column('delivered', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_support_requests_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_support_requests'))
    )
    op.create_index(op.f('ix_support_requests_user_id'), 'support_requests', ['user_id'], unique=False)
    op.create_table('user_performance_summary',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('level_id', sa.Integer(), nullable=False),
    sa.Column('age_group', sa.String(length=16), nullable=True),
    sa.Column('attempts_total', sa.Integer(), nullable=False),
    sa.Column('pass_count', sa.Integer(), nullable=False),
    sa.Column('answers_total', sa.Integer(), nullable=False),
    sa.Column('total_answer_time_ms', sa.Integer(), nullable=False),
    sa.Column('total_timer_utilization', sa.Float(), nullable=False),
    sa.Column('first_try_passes', sa.Integer(), nullable=False),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_performance_summary_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'level_id', name=op.f('pk_user_performance_summary'))
    )
    op.create_table('user_progress',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('highest_level_completed', sa.Integer(), nullable=False),
    sa.Column('levels_completed_count', sa.Integer(), nullable=False),
    sa.Column('total_score', sa.Integer(), nullable=False),
    sa.Column('last_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_progress_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_user_progress'))
    )
    op.create_table('leaderboard_entries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('attempt_id', sa.Uuid(), nullable=False),
    sa.Column('level_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('is_under_13', sa.Boolean(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['level_attempts.id'], name=op.f('fk_leaderboard_entries_attempt_id_level_attempts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_leaderboard_entries_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_leaderboard_entries')),
    sa.UniqueConstraint('attempt_id', name=op.f('uq_leaderboard_entries_attempt_id'))
    )
    op.create_index(op.f('ix_leaderboard_entries_level_id'), 'leaderboard_entries', ['level_id'], unique=False)
    op.create_index(op.f('ix_leaderboard_entries_recorded_at'), 'leaderboard_entries', ['recorded_at'], unique=False)
    op.create_index(op.f('ix_leaderboard_entries_revoked'), 'leaderboard_entries', ['revoked'], unique=False)
    op.create_index(op.f('ix_leaderboard_entries_score'), 'leaderboard_entries', ['score'], unique=False)
    op.create_index(op.f('ix_leaderboard_entries_user_id'), 'leaderboard_entries', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_leaderboard_entries_user_id'), table_name='leaderboard_entries')
    op.drop_index(op.f('ix_leaderboard_entries_score'), table_name='leaderboard_entries')
    op.drop_index(op.f('ix_leaderboard_entries_revoked'), table_name='leaderboard_entries')
    op.drop_index(op.f('ix_leaderboard_entries_recorded_at'), table_name='leaderboard_entries')
    op.drop_index(op.f('ix_leaderboard_entries_level_id'), table_name='leaderboard_entries')
    op.drop_table('leaderboard_entries')
    op.drop_table('user_progress')
    op.drop_table('user_performance_summary')
    op.drop_index(op.f('ix_support_requests_user_id'), table_name='support_requests')
    op.drop_table('support_requests')
    op.drop_index(op.f('ix_questions_variant_type'), table_name='questions')
    op.drop_index(op.f('ix_questions_review_status'), table_name='questions')
    op.drop_index('ix_questions_pool_lookup', table_name='questions')
    op.drop_index(op.f('ix_questions_linked_character_id'), table_name='questions')
    op.drop_index(op.f('ix_questions_level_id'), table_name='questions')
    op.drop_index(op.f('ix_questions_active'), table_name='questions')
    op.drop_table('questions')
    op.drop_index(op.f('ix_purchase_records_user_id'), table_name='purchase_records')
    op.drop_index(op.f('ix_purchase_records_unlock_status'), table_name='purchase_records')
    op.drop_index(op.f('ix_purchase_records_transaction_id'), table_name='purchase_records')
    op.drop_index(op.f('ix_purchase_records_original_transaction_id'), table_name='purchase_records')
    op.drop_table('purchase_records')
    op.drop_index(op.f('ix_parental_consent_records_verification_token_hash'), table_name='parental_consent_records')
    op.drop_index(op.f('ix_parental_consent_records_status'), table_name='parental_consent_records')
    op.drop_index(op.f('ix_parental_consent_records_child_user_id'), table_name='parental_consent_records')
    op.drop_table('parental_consent_records')
    op.drop_table('level_completions')
    op.drop_index('ix_level_attempts_user_level', table_name='level_attempts')
    op.drop_index(op.f('ix_level_attempts_user_id'), table_name='level_attempts')
    op.drop_index(op.f('ix_level_attempts_status'), table_name='level_attempts')
    op.drop_index(op.f('ix_level_attempts_level_id'), table_name='level_attempts')
    op.drop_index(op.f('ix_level_attempts_install_id'), table_name='level_attempts')
    op.drop_table('level_attempts')
    op.drop_index(op.f('ix_auth_identities_user_id'), table_name='auth_identities')
    op.drop_table('auth_identities')
    op.drop_index('ix_analytics_user_event', table_name='analytics_events')
    op.drop_index(op.f('ix_analytics_events_user_id'), table_name='analytics_events')
    op.drop_index(op.f('ix_analytics_events_timestamp_utc'), table_name='analytics_events')
    op.drop_index(op.f('ix_analytics_events_session_id'), table_name='analytics_events')
    op.drop_index(op.f('ix_analytics_events_event_name'), table_name='analytics_events')
    op.drop_index(op.f('ix_analytics_events_admin_user_id'), table_name='analytics_events')
    op.drop_index('ix_analytics_event_name_time', table_name='analytics_events')
    op.drop_table('analytics_events')
    op.drop_index(op.f('ix_ad_impression_logs_user_id'), table_name='ad_impression_logs')
    op.drop_index(op.f('ix_ad_impression_logs_impressed_at'), table_name='ad_impression_logs')
    op.drop_table('ad_impression_logs')
    op.drop_index('ix_users_mobile_name', table_name='users')
    op.drop_index(op.f('ix_users_mobile'), table_name='users')
    op.drop_index(op.f('ix_users_install_id'), table_name='users')
    op.drop_index(op.f('ix_users_account_status'), table_name='users')
    op.drop_table('users')
    op.drop_table('rate_limit_counters')
    op.drop_table('levels')
    op.drop_table('content_publish_records')
    op.drop_index(op.f('ix_bible_characters_review_status'), table_name='bible_characters')
    op.drop_index(op.f('ix_bible_characters_name'), table_name='bible_characters')
    op.drop_table('bible_characters')
    op.drop_index(op.f('ix_audit_logs_target_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_occurred_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_admin_users_email'), table_name='admin_users')
    op.drop_table('admin_users')
    # ### end Alembic commands ###
