"""kids zone stop completions

Revision ID: af1621646cd3
Revises: 6c76280f0b0b
Create Date: 2026-09-11 20:30:55.555679
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = 'af1621646cd3'
down_revision = '6c76280f0b0b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kids_zone_stop_completions',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('stop_id', sa.String(length=64), nullable=False),
    sa.Column('adventure_id', sa.String(length=64), nullable=False),
    sa.Column('best_stars', sa.Integer(), nullable=False),
    sa.Column('completions_count', sa.Integer(), nullable=False),
    sa.Column('first_completed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_completed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_kids_zone_stop_completions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'stop_id', name=op.f('pk_kids_zone_stop_completions'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('kids_zone_stop_completions')
    # ### end Alembic commands ###
